openapi: 3.0.0
info:
  title: Golang Auth API
  version: 1.0.0
paths:
  /api/user/register:
    post:
      summary: Регистрация нового пользователя
      requestBody: ...
      responses: ...
  /api/token:
    post:
      summary: Получение JWT по email+пароль
      requestBody: ...
      responses: ...
  /api/secured/ping:
    get:
      security:
        - bearerAuth: []
      summary: Проверка доступа к защищенному endpoint
      responses: ...

