

@host = localhost:8080

// Регистрируем пользователя
// Не забыть: отправляем запросы с помощью REST Client через VSCode
POST http://{{host}}/api/user/register HTTP/1.1 content-type: application/json

{
    "name": "dmitry chushov", 
    "username": "chushov", 
    "email": "chushov@yandex.ru", 
    "password": "1234567890"

}

###
