

@host = localhost:8080

// Регистрируем пользователя
POST http://{{host}}/api/user/register HTTP/1.1 content-type: application/json

{
    "name": "user username", 
    "username": "username", 
    "email": "user@mail.mail", 
    "password": "1234567890"

}
###
